apiVersion: apps/v1
kind: Deployment
metadata:
  name: flixpredix-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flixpredix
      service: admin
  template:
    metadata:
      labels:
        app: flixpredix
        service: admin
    spec:
      containers:
      - name: flixpredix-admin
        image: europe-west4-docker.pkg.dev/flixpredix/flixpredix/flixpredix-admin:latest
        ports:
        - containerPort: 8080