apiVersion: apps/v1
kind: Deployment
metadata:
  name: flixpredix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flixpredix
      service: server
  template:
    metadata:
      labels:
        app: flixpredix
        service: server
    spec:
      containers:
      - name: flixpredix-server
        image: europe-west4-docker.pkg.dev/flixpredix/flixpredix/flixpredix-server:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3